groups:
  - name: example
    rules:
      - record: code:prometheus_http_requests_total:sum
        expr: 100- ((node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes) / node_memory_MemTotal_bytes * 100)